language: php
php:
  - '8.1.0'

services:
  - mysql

before_script:
  - composer install

script:
  - php bin/phpunit
  - php bin/phpunit tests/Entity/TaskTest.php
  - php bin/phpunit tests/Controller/DefaultControllerTest.php